### ISSUE TITLE
How can I remove the tag?

### ISSUE THREAD

**Issue by flurmind** [AlexSciFier/neonlink#104]
I have empty tags on my links page. I can't delete them.
![neon](https://github.com/AlexSciFier/neonlink/assets/104086752/756016f1-c8dd-4785-99d8-4f59b05c42ff)

**Comment by flurmind** [comment]
The problem is still there in the following cases:
1) Empty tag without text (was accidentally saved when I was typing a few words with a space in one tag);
2) Empty tag in Russian language.

**Comment by AlexSciFier** [comment]
Should be fixed in 1.4.16
