### ISSUE TITLE
[Issue] "Number of columns in dashboard" not working

### ISSUE THREAD

**Issue by mrekin** [AlexSciFier/neonlink#18]
Hi.

_Version 1.2.4, 
Docker._

Seems "Number of columns in dashboard" property does not work.
I have 5 groups, set value from 1 to 6 - no changes at dashboard page..

**Comment by AlexSciFier** [comment]
Fixed in 1.2.5
https://github.com/AlexSciFier/neonlink/releases/tag/v1.2.5
