### ISSUE TITLE
URL Editing Bug

### ISSUE THREAD

**Issue by WhyWolfie** [AlexSciFier/neonlink#20]
Using: NodeJS.
Imported all my URLS from my browser.

Trying to add too my Group, But i can't edit URL.
![image](https://user-images.githubusercontent.com/59147206/205166831-52349ae6-4d5f-4291-93e3-d41c1e82e75f.png)

Another issue i can't remove my URL from the group too.

![image](https://user-images.githubusercontent.com/59147206/205167397-bcbd0fb0-94ea-45a0-a61c-fb737e433409.png)

Only if I have to delete the whole group

**Comment by AlexSciFier** [comment]
Fixed in 1.2.5
https://github.com/AlexSciFier/neonlink/releases/tag/v1.2.5

> Another issue i can't remove my URL from the group too.

Change url category to None
