### ISSUE TITLE
arm64/v8 support?

### ISSUE THREAD

**Issue by y0nei** [AlexSciFier/neonlink#27]
any plans for support on that architecture? for now it works on arm/v7 but im having issues running it on a raspberry pi 4

**Comment by AlexSciFier** [comment]
Hi! I built and uploaded latest (1.2.5) image to DockerHub for arm64/v8 architecture. Please, check it out. [alexscifier/neonlink:latest-arm64v8](https://hub.docker.com/layers/alexscifier/neonlink/latest-arm64v8/images/sha256-9c225edd5c08a838fef66aedc84e173708515d1b4b5707b485e865e46d66627e?context=repo)
