### ISSUE TITLE
[Bug] Background images are not working

### ISSUE THREAD

**Issue by AuthorShin** [AlexSciFier/neonlink#28]
Hello
Thanks for making this beautiful simple self-hosted bookmark service.
Background images are not working from time to time plus the sync setting option is resetting all the time.
Also I would like to have backgrounds even on dark mode.

**Comment by AlexSciFier** [comment]
Hello, thank you for your feedback! All settings stores in browser in localStorage. When you acess Neonlink from other device by default uses settings in browser, thats why sync settings doesn't turn on by default. When you enable sync settings than all your settings including background image is loaded. (Might need to reload page)

Background image works both in dark and light mode.

**Comment by AuthorShin** [comment]
Hmmm, so does that mean if I open it in "Private mode" of my browser it might just not work?

**Comment by AlexSciFier** [comment]
Yes, in private mode all your cookies and localStorage is empty. It's basically a new device.

**Comment by AuthorShin** [comment]
Oh so maybe that's why these options are not working.
Any way to make it work on private mode?

**Comment by AlexSciFier** [comment]
When you opened app go to settings, turn on sync options and refresh page. This is the only solution so far.

**Comment by AuthorShin** [comment]
Here in this video I demonstrate how it's not working:

https://user-images.githubusercontent.com/4959043/210065674-7e810dbe-342b-4620-836e-abf15e7abd8f.mp4

**Comment by AlexSciFier** [comment]
Ok, i see. You forgot to enable "Use image as background" option
![image](https://user-images.githubusercontent.com/66871322/210066124-64fe7a44-037e-4279-a039-820191a144aa.png)

**Comment by AuthorShin** [comment]
Oh, my bad.
But it's working until the tab is open. If I close the tab but not the window and reopen the neonlink all the settings, including sync and dark mode the same as I selected in the previous tab but the "Use image as background" option and the selected image will reset and I have to select them again although I haven't close the window of the browser yet and it's still the same session.

**Comment by ItsNoted** [comment]
Background images are not working for me either. I tried both Chrome and Firefox browsers. Also, I enabled the "Use background image" selector. I am not using the private browsing mode either. Strange.

**Comment by AlexSciFier** [comment]
What version of the application are you using? Did you correctly specify the volume in docker-compose? Can you provide docker image logs?

**Comment by Tataukee** [comment]
Background Image is npt working ..
EACCES: permission denied
Any idea ?

**Comment by AlexSciFier** [comment]
Hello @Tataukee. This is issue with docker permission. This might help you #58.

**Comment by Tataukee** [comment]
Hello @AlexSciFier . You are right . I had to give RW permission to the main folder and voilà . Background image set as wishes . Thank you so much.
