### ISSUE TITLE
Request body is too large

### ISSUE THREAD

**Issue by PDXUser** [AlexSciFier/neonlink#3]
I am trying to import my Firefox Bookmarks and  I get the following error when attempting to import them:

>     today at 8:28:31 PM err.code=FST_ERR_CTP_BODY_TOO_LARGEerr.message=Request body is too largeerr.name=FastifyErrorerr.stack=FastifyError: Request body is too large at rawBody (/app/server/node_modules/fastify/lib/contentTypeParser.js:188:16) at ContentTypeParser.run (/app/server/node_modules/fastify/lib/contentTypeParser.js:146:5) at handleRequest (/app/server/node_modules/fastify/lib/handleRequest.js:37:39) at runPreParsing (/app/server/node_modules/fastify/lib/route.js:451:5) at next (/app/server/node_modules/fastify/lib/hooks.js:158:7) at /app/server/node_modules/fastify-cors/index.js:127:12 at resolveOriginOption (/app/server/node_modules/fastify-cors/index.js:85:129) at onRequest (/app/server/node_modules/fastify-cors/index.js:87:3) at Object. (/app/server/node_modules/fastify-cors/index.js:29:7) at hookIterator (/app/server/node_modules/fastify/lib/hooks.js:237:10)err.statusCode=413err.type=FastifyErrorhostname=89a4727c08f3level=30msg=Request body is too largepid=19reqId=req-tres.statusCode=413time=1663817311054

There are a total of 298 bookmarks in which I am trying to add.

**Comment by AlexSciFier** [comment]
Hi! By default the file size limit is 1MiB. I'll fix this in future update.

**Comment by AlexSciFier** [comment]
Fixed in 1.1.1
