### ISSUE TITLE
Invalid Date for imported links

### ISSUE THREAD

**Issue by miguelns21** [AlexSciFier/neonlink#30]
I have import several link from html.

In list they show "Invalid date"

**Comment by AlexSciFier** [comment]
Hello. Seems like your html file doesn't contain a date information. Can you tell me where you get your html file?

**Comment by miguelns21** [comment]
Safari export.El 14 ene 2023, a las 12:13, AlexSciFier ***@***.***> escribió:﻿
Hello. Seems like your html file doesn't contain a date information. Can you tell me where you get your html file?

**Comment by AlexSciFier** [comment]
Fixed in 1.2.6
