### ISSUE TITLE
Unable to Edit Links

### ISSUE THREAD

**Issue by GianniBYoung** [AlexSciFier/neonlink#35]
I followed the setup instructions for docker and added a few links. One of the links did not have an icon associated with it so I tried to edit it and was able.

Steps To Reproduce:
1. Create link
2. Click the link tab
3. Click the right arrow symbol next to link and then the pencil icon.
4. The link is greyed out and can't be edited (other fields can be updated however).
5. Click the edit button 
6. Edit button returns to link tab page.

docker-compose version 1.26.0, build d4451659
5.19.0-35-generic #36~22.04.1-Ubuntu

**Comment by AlexSciFier** [comment]
HI, you can't edit url of saved link. If you want to change icon you can provide link to your icon in the input box below url.

**Comment by GianniBYoung** [comment]
Gotcha, is this functionality planned to be implemented?

**Comment by AlexSciFier** [comment]
No, i didn't plan to implement this.

**Comment by GianniBYoung** [comment]
Thanks for the clarification, I will mark this one as closed
