### ISSUE TITLE
Add option Nologin

### ISSUE THREAD

**Issue by robotsflo** [AlexSciFier/neonlink#5]
Hi, 
Can you add an option to use the bookmark service without authentifications and just with an "default Account" ?

Thanks a lot for the good job

**Comment by AlexSciFier** [comment]
Hello, thanks for your suggestion! This application is designed as a private storage for personal bookmarks. I didn't expect anyone to want to make their bookmarks public. But if you use this application only on the local network, then in this case it makes sense to add this feature.

**Comment by robotsflo** [comment]
That’s right. I will post this feature because i use it only on my private network and, i share my bookmark with family. Use login and password : admin:admin at any use is ok but I’m lazy. I would like to auto login as grafana with viewer default profil or just bypass login for full acces to the app.

**Comment by AlexSciFier** [comment]
The NoLogin option was added in version 1.2.0.

**Comment by xrfmkrh** [comment]
I like this option but it's gone after v.1.4.x
Can you plz add it again?
Thanks.

**Comment by AlexSciFier** [comment]
It is still exist. In Settings - Main - Authentication

**Comment by xrfmkrh** [comment]
If I disable Authentication, then my bookmarks all gone.(not deleted but not shown)
And when i click Settings it says 'Error - Authentication must be enabled'.

**Comment by AlexSciFier** [comment]
Fixed in 1.4.5

**Comment by xrfmkrh** [comment]
It works. Thanks!
But without cookies, interface settings not saved. So Columns in dashboard are always one.(cuz my browser delete cookies whenever i close browser)  is it right?

**Comment by xrfmkrh** [comment]
Alright. Thanks a lot!
