### ISSUE TITLE
Session and user security bug

### ISSUE THREAD

**Issue by julichan** [AlexSciFier/neonlink#51]
Hello,

It seems that a session cookie last 8 months and that the token is reused past those 8 months. The token is also used in database on various tables as primary keys.

This is a major security bug for those who expose neonlink on the web. Even protected by ssl/tls encryption, all network request are breakable within 3 months or less. This means a hacker may gain access to neonlink by retriving the session token. 

The token needs to be renewable at least everyday even if it last longer.

Additionaly, the password can be broken the same way, it is passed in clear in login requests. a policity to change it every 3 months should be added and a more secure way of transmission is required.

A good solution to get past those security problems would be to considere sso implementation?

In https://github.com/AlexSciFier/neonlink/pull/50 pull request, i've started to get rid of the session token within database tables and make the session token renewable but this won't be enough. More action should be taken.

At first, it may seem that the information retrivable from neonlink is not sensible but it is actually critical as it could allow hackers to cross-link informations on an individual.

**Comment by AlexSciFier** [comment]
Hello, thank you for you work and your offers.
Some users use Neonlink only on the local network. Therefore, I think that the security rules should not be so strict. We can make them optional.
For example:
> It seems that a session cookie last 8 months and that the token is reused past those 8 months.

We can make a setting where user can decide, how long shoud session cookie expire. 

> The token needs to be renewable at least everyday even if it last longer.

We can renew token on every login.

> Additionaly, the password can be broken the same way, it is passed in clear in login requests. a policity to change it every 3 months should be added and a more secure way of transmission is required.

Again, we can make this as optional settings.

I think we shoud switch to the JWT tokens instead of session id.

**Comment by AlexSciFier** [comment]
> A good solution to get past those security problems would be to considere sso implementation?

Does i get it right? You mean SSO as Single Sign-On? I think this is overkill. Why do we need this?

**Comment by julichan** [comment]
Alright, I did implement my propositions in the last commit. The cookie is deleted and recreated with a new id if it's more than one day old. The session table is now separate from the user so this remains lightweight.

As for your proposition for JWT, there are two schools, I'm from the school that doesn't trust it at all. My reasons ? well a jwt token is an encrypted object containing user informations. I believe that's way worse that a sessionId. like hard drive storage, if the object is captured (by a man in the middle attack in this case), the data can be recovered easily with a dictionary attack and then used to try to hack into the site. 

The session id is just a string so it doesn't contain sensible data. the data is safer on server side and we can protect it against simple dos-like dictionary attacks by bannishing an ip or blocking a user from login a certain amount of time from a excess of login tries.

Yes, SSO is Single Sign On. I don't think this is overkill but it could be a safer option as we could let the sso server side handle the security of the login. Beside people who install you app are usually people who know to deploy such an application, if I'm not wrong. Those people install a lot of apps and connect them all to a sso to have a single login/password.

**Comment by julichan** [comment]
> Hello, thank you for you work and your offers

You are welcome. I'm just trying to give my all in a short period of time to get my need without breaking your work. 👍
