### ISSUE TITLE
[BUG] Twitter link has no icon

### ISSUE THREAD

**Issue by mariushosting** [AlexSciFier/neonlink#69]
Twitter links now X don't show any icon when I add someone link profile.

**Comment by AlexSciFier** [comment]
Hello, I think this is an issue with twitter. All other sites from Meta works fine.

**Comment by mariushosting** [comment]
> Hello, I think this is an issue with twitter. All other sites from Meta works fine.

Unfortunately the issue is only with NeonLink, can't replicate using other docker bookmarks.

**Comment by AlexSciFier** [comment]
Should work in 1.4.12
