### ISSUE TITLE
Wrong version in  settings about in release v 1.4.9

### ISSUE THREAD

**Issue by abaranyi** [AlexSciFier/neonlink#74]
Hi,
I am using the latest neonlink 
and it shows in settings about:

Open-source self-hosted bookmark service

Version 1.4.8

New version v1.4.9 available for update!

I checked the master and you missed to update the frontend/src/helpers/constants.js
in master it is:
export const VERSION = "1.4.8";

and it should be export const VERSION = "1.4.9";

**Comment by AlexSciFier** [comment]
I changed versioning method in #75. Should be fixed in 1.4.10
