### ISSUE TITLE
The same problem again: problem with character encoding and icons on some russian sites?

### ISSUE THREAD

**Issue by flurmind** [AlexSciFier/neonlink#77]
I use some Russian torrent trackers ([https://kinozal.tv](https://kinozal.tv)) and they have a problem with character encoding.
![toorent](https://github.com/AlexSciFier/neonlink/assets/104086752/1f5fde90-48bc-4092-80d5-b5879a04df68)
And a lot of Russian sites don't have icons (https://www.avito.ru, https://www.ozon.ru etc.). Why are the icons not parsing? Thank's!

**Comment by AlexSciFier** [comment]
Should be fixed in 1.4.11
