### ISSUE TITLE
There is a problem with parsing on many Russian online shopping sites (errors 401, 403...)

### ISSUE THREAD

**Issue by flurmind** [AlexSciFier/neonlink#81]
There is a problem with parsing on many Russian online stores sites when adding new links (errors 401, 403...):
**Logs:**
`Setting umask to 22
Creating database and backgrounds directories
User set by docker; running Neonlink as 1000:1000
Config plugin initialization completed.
Database plugin initialization completed.
Life cycle plugin initialization completed.
Starting migrations...
Found database version 6
Found 0 applicable migration files.
Migrations completed.
Application initialized.
Server started listening on http://0.0.0.0:3333
https://www.dns-shop.ru Request failed with status code 401
https://www.dns-shop.ru Request failed with status code 401
https://www.dns-shop.ru Request failed with status code 401
ozon.ru connect ECONNREFUSED 127.0.0.1:80
https://ozon.ru Request failed with status code 403
https://ozon.ru Request failed with status code 403
https://ozon.ru Request failed with status code 403
https://ozon.ru Request failed with status code 403
wildberries.ru connect ECONNREFUSED 127.0.0.1:80
https://www.vseinstrumenti.ru Request failed with status code 403
https://www.vseinstrumenti.ru Request failed with status code 403
https://www.vseinstrumenti.ru Request failed with status code 403
https://www.vseinstrumenti.ru Request failed with status code 403
https://www.vseinstrumenti.ru Request failed with status code 403
https://www.vseinstrumenti.ru Request failed with status code 403
avito.ru connect ECONNREFUSED 127.0.0.1:80
https://avito.ru Request failed with status code 403
https://avito.ru Request failed with status code 403
`

Is it an error of my server settings or is it a configured blocking of parsing on these sites?

Can you help to understand?))
Thanks!!!

**Comment by AlexSciFier** [comment]
The application sends requests without any cookies or user-agent. Many sites do not like this behavior and block the connection if many requests of the same type are received. Try updating the links later, perhaps the blocking will go away by this time.

**Comment by AlexSciFier** [comment]
I looked at the dns-shop website and it has parsing protection. Roughly speaking, the html code is issued only for a real browser (I think other sites on the list use similar technology). And although bypassing the protection can be done through a headless browser, I don’t see the point in overcomplicating the application so much.
I will make it so that the application will try to parse the title and icon even if the status is 4xx or 5xx.
