### ISSUE TITLE
Link in new tab - Disabling has no effect

### ISSUE THREAD

**Issue by NighthawkUK** [AlexSciFier/neonlink#84]
As title states, unchecking the 'Link in new tab' option will still have the bookmark links open in a new tab rather than the current tab. I've tried toggling on and off to see if that will fix/reset it but nothing.

**Comment by AlexSciFier** [comment]
Yes. Links in the Control Panel ignore the "Link in New Tab" option. Need to add this feature to the control panel as well.

**Comment by NighthawkUK** [comment]
Thank you!
